version: 2

sources:
  - name: airstats
    schema: raw
    tables:
      - name: airports
        identifier: airports
# this file creates an extra abstraction on top of our raw layer
# and now I can reference my raw tables as my source tables
# example: see how we reference it in models/src/src_airports.sql, example:
#          {{ source ('airstats', 'airports') }}
        description: "Global airport data (~72K rows)"
        columns:
          - name: id
            tests:
              - dbt_expectations.expect_column_values_to_be_of_type:
                  arguments:
                    column_type: NUMBER
          - name: ident
            tests:
              - dbt_expectations.expect_column_values_to_be_of_type:
                  arguments:
                    column_type: VARCHAR

              - dbt_expectations.expect_column_values_to_be_unique

          - name: type
            tests:
              - dbt_expectations.expect_column_values_to_be_of_type:
                  arguments:
                    column_type: VARCHAR
              - dbt_expectations.expect_column_values_to_be_in_set:
                  arguments:
                    value_set: ['small_airport', 'medium_airport', 'large_airport', 'heliport', 'seaplane_base', 'balloonport', 'closed']
          
          - name: name
            tests:
              - dbt_expectations.expect_column_values_to_be_of_type:
                  arguments: 
                    column_type: VARCHAR
          - name: iso_country
            tests:
              - dbt_expectations.expect_column_values_to_be_of_type:
                  arguments:
                    column_type: VARCHAR

      - name: comments
        identifier: airport_comments
        description: "User comments about airports"
        columns:
          - name: id
          - name: airport_ref
          - name: airport_ident
          - name: subject
          - name: body
          - name: date
      
      - name: runways
        identifier: runways
        description: "Runway information (~44K rows)"
        columns:
          - name: id
          - name: airport_ref
          - name: airport_ident
          - name: closed
